### ISSUE TITLE
Fix References

### ISSUE THREAD

**Issue by qjhart** [qjhart/ahb-pnw.hart14model-poplar#3]
Finally the references are just bad - I have provided our extended revision instructions so that you can both understand the units issue, and sort out the references.
However, if you feel that you can suitably address the reviewers' comments (included below), I invite you to revise and resubmit your manuscript within 60 days.

**Comment by qjhart** [comment]
@peteWT Argh, didn't look like you even started this.  The bibliography style doesn't match so I've started a file hart14model-poplar-custom.bbl, but that has to be made by hand, and there are 4 missing references.

**Comment by qjhart** [comment]
@peteWT, OK I think you are right, the Vancouver.bst file seems to do a really nice job (It's in texlive-publishers on debian)  I've updated the bib file.  I did take out the url and doi citations from the ahb-pnw.bib file, I think they aren't supposed to be added for B&B.

**Comment by qjhart** [comment]
There still seem to be about 14 warnings in bibtex from missing citations, and missing parts of bibtex records.

**Comment by peteWT** [comment]
@qjhart I guess I didn't commit my changes last time. Many edits (removing Cooke reference, etc) had not been incorporated in the version you last reviewed. Ive since incorporated them...
