### ISSUE TITLE
Reviewer #5 Edits

### ISSUE THREAD

**Issue by qjhart** [qjhart/ahb-pnw.hart14model-poplar#8]
- [x] Highlight number 2, please replace "exsiting" with existing
- [x] Page 2.  Please provide a brief overview about the 3PG model, to understand how the growth is modeled and what are the main parameters? How the parameters are adjusted? What are the assumptions and simplifications of the 3PG model?
- [x] Page 2, line 27.  There is no validation of the 3PG model for coppiced SRWC against empirical data.
- [x] Page 3 Lines 61-62.  What field studies were used to validate the 3PG model? Please cite or report the methods you used to compare the model to actual data.  I think this part corresponds to the methods not the introduction.
- [x] Page 3, line 65.  I think the climate change scenario is out of the scope of this study.  It is more important to validate the model first before making assumption and modeling different scenarios.
- [x] Page 4, line 85.  What are the implications in relation to the model results of having such a large pixel size?  I understand that having such a large pixel size reduce complexity but it is not clear (or discussed) how accuracy and quality of the results could be affected.  Discuss or cite literature that had used a similar approach with good quality results.
- [x] Page 5, figure 1, I would suggest eliminating figure 1, since it adds very little to the description section.
- [x] Page 6 line 105.  How sensitive is the model to the monthly step run?  Does the result from the model growth would be different if the 3PG model is run at daily or yearly timestep?
- [x] Page 6 line 113.  There is no reference provide in cite # 8.  Is that an internal report of a review from the authors?  Is this report available for reader of the article?
- [x] Page 6  lines 117 to 122:  Is there any empirical data to compared root contribution modeled against real?
- [x] Page 7, figure 2.  Is there any hierarchy in the graph?  Some elements are not connected, so it is not clear how the different inputs are related.
- [x] Page 8, line 125. Explain when conditions are favorable and not favorable.  Do favorable (and unfavorable) conditions change across the region?
-  [x] Page 8, line 131.  Revise cite 8.
- [x] Page 9, line 165-166 .  What are the assumptions when ground stations are not available no validate the data?
- [x] Page 10 and 11, how does pixel size of mean annual temperature and annual rainfall raster compares to the pixel size used to do the grid partitions of the region?  In other words if a grid pixel contains two different rainfall pixels, what rainfall values is assumed for the grid partition?
- [x] Page 9-12.  I would prefer to have a table of the 3PG parameters estimates used in the model to show the value used, the units and the source.
- [x] Page 16, line 244.  I would suggest the auhors to concentrate in the model validation before analyzing climte change scenarios.
- [x] Page 16, line 246.  Explain in which consist A1B scenario or provide a citation. Is there any particular reason Why this scenario was selected?
- [x] Page 19, line 275.  I would be good to explain in the introduction how poplar is managed for liquid fuels production.
- [ ] Page 22, lines 355 to 363.  Conclusion section needs to be strengthened. Explain what the limitations of the model are. Also how the model is affected by the parameter and how modeled grow compares to actual growth of poplar plots.

**Comment by peteWT** [comment]
Response to p3 line65. The validation has been added and the climate change scenario retained.
