### ISSUE TITLE
Reviewer #3 Edits

### ISSUE THREAD

**Issue by qjhart** [qjhart/ahb-pnw.hart14model-poplar#9]
Reviewer 3 included a PDF file with a number embedded comments.  These will be addressed by referencing the line number:
- [X]  51 - Fixed complicated sentence
- [x] 55 - Acknowledge and discuss other approaches to this problem (e.g. Deckmyn et al, Amichev et al.).  How do their approaches differ from your's.  Which one is preferable and explain why. 
- [x] 59 - Upon what is this based?  Justify the proportion of root stores using authorities showing this is accurate.  
- [x] 61 - Methods These are methods, details of which don't belong in the introduciton.  Cite peer-reviewed authorities where validation took place.  
- [x] 64 -Again, this does not belong in the introduction.   It should be described in the results.
- [x] 66 Results
- [X] 88 Note about citatation
- [x] 90 Binary information
- [x] 97 - Describe these calculations.  Even someone with expert knowledge could not understand and duplicate this approach.
- [x] 103 Redundant use of soil parameters in this sentence.
- [x] 109 - Modify this to something like: "... allocates biomass production from photosynthesis..."  No production results directly from transpiration.  This confusion between transpiration and photosynthesis also appears in the Quinn et al 2014 publication.   Of course, transpiration and photosynthesis occur simultaneously when stomata are open, which might suggest transpiration drives production, but it is photosynthesis that directly assimilates the carbon used to produce biomass while water vapor is lost from the leaf through the process of transpiration.  
- [x] 113 The reference presented does not meet the reference style. Include institute for which report is written, report number and URL.
- [x] 115 Redundant use in this sentence of this uncommon word.  Rephrase to eliminate redundancy.  I suggest using common simple synonym such as "excess"
- [x] 115 How much is used, and what is the basis for selecting that specific amount.
- [x] 116 Incomplete thought.  Apparently the original model begins to supply new biomass once some level of canopy has developed.  
- [x] 117  can't make sense out of this sentence.  
- [x] 119 What difference?  No previous mention of a difference.  I guess the comparison between actual to potential is calculated as a difference?
- [x] 121 It is not apparent when in the coppice regrowth this is describing.  
- [x] Figure 2. Parameters (Credit inspiration for this figure, e.g. Landsberg and Sands Fig 9.1, etc.)
- [x] 123 To say that regrowth is timed with climate is not accurate because it implies that time is controlling growth.  Actually, climate is controlling growth and both climate and growth are correlated with the time of year.  Causation of growth in this case is climate, not time.  Very different timing of
- [x] 131 Remove
- [x] 135 This appears to result from the fact that there was a wide range of parameters from Hart et al (2014) trying to fit multiple clonal growth responses.  The parameters and their values included in each of the six sets should be presented for the reader to understand how the various parameter sets vary.  Furthermore, the presentation should include justification for varying the various parameter sets.  This is especially important if some parameter is changed that has typically been set at the default level for other 3PG parameter sets.
- [X] 137 This section is OK
- [x] 151 Sixteen ? I guess
- [x] 154 -Figure 4 shows
- [x] Figure 4  Total Annual Rainfall (precipication vs. rainfall)
- [x] 205 Poplar
- [x] 208 - Bad Reference
- [x] 212 - Figure 10 is yield for irrigated crops not some sort of masked area without high slope and salinity.
- [X ] 257 spatial and Spatial
- [x] 271 Move stuff to methods
- [x] 273 Justify using deferent parameter sets.  Implies uncertainty in which parameters to use.  Revise sentence to eliminate "was run ... were run" confusion.
- [x] 274 Placing this statement around line 135 would help avoid the ensemble confusion.  In fact, all statements in this first paragraph of the Results section belong in Methods section.
- [ ] 275 Do you mean an 18 year total lifetime?
- [ ] 283 Lines 278-279 describe expressing on "per year basis", i.e. Mg/ha/year, or NPP.  But these units suggest that this is cumulative yield over 18 years.  The values are too large to be expressed on a per year basis, which suggests lines 278-9 should be modified to something like cumulative annual yield.  See table in the AHB overview article showing annual NPP (http://www.extension.org/pages/70456/poplar-populus-spp-trees-for-biofuel-production#.VH9_FWf-mpE)
- [x] 286 Be specific, this is not a term commonly used to describe any region of the PNW.  
- [X] 305 Bad Figure reference Fixed
## Bibliography Fixes

-[x] 384 
-[ ] 387 
-[ ] 395
## Long note about
- [X] 131 Hart et al (2014) is a non-refereed publication that intends to describe the logic used for implementing and validating the coppice modification to 3PG.  Review of that publication leaves numerous questions about the basis for the model implementation and raises concern about the accuracy of predictions due to uncertain model parameterization.  Questions include: What physiological process determines target LAI ?  A logic gate controlling productive potential flowing from the roots to support shoot growth occurs when target LAI reaches zero.   How does target LAI change with coppice development?  There is a partitioning factor built into 3PG.  Hart et al (2014) say that the factor pR%x "defines the root size with respect to the total plant biomass", which contrasts with Sands 2010 3PG User Manual which describes pRx as the maximum fraction of NPP partitioned to roots.  So Hart et al use it to describe a pool and Sands defines it as a flux.  How to rectify these contrasting definitions and the use of pR%x in Hart et al's equation (4) where it appears that a flux is subtracted from a pool?

The validation data sets used in Hart et al (2014) use different parameters for the various clones.  It is not clear what parameter sets are appropriate for clones used to project production potential regionally. Unfortunately, the parameters used to fit experimentally derived output data, the value ranges of parameters used, and a systematic approach for selecting parameters and their range are not presented.

Given these open questions about the implementation of the model, and uncertain parameterization, the subsequent validation is not solid.  To use such a base upon which to project poplar growth regionally is worrisome.  In order for regional projections to be on a solid footing, the information in Hart et al 2014 should be published in a refereed journal after passing the review of experts in physiological growth process models.

**Comment by qjhart** [comment]
@peteWT pushed the PDF to ~/jbb-reviews

**Comment by peteWT** [comment]
@mclay120 Need to change the text in Figure 3 (Rainfall map) to say 'Rainfall' in stead of 'Precipitation'.
@qjhart

**Comment by peteWT** [comment]
@qjhart need to identify units on maps 9-11. And in the text per the comment above...

**Comment by qjhart** [comment]
Actually @mclay120 let me double check on the change from precipitation to rainfall, if we get that from PRISM, it might be precipitation.

**Comment by peteWT** [comment]
@qjhart Still need to resolve the issue with units in the maps and on lines 278-9 in the draft as submitted. Article text and map legend says Mg/ha but the caption in figure 8 says 'annual'. I've edited to reflect annualized yield. Change if wrong or check box above if right..

**Comment by qjhart** [comment]
@peteWT , the are both wrong.  It's the Yield from one 3 year coppice cycle.  I've modified the figures, and have gone through the text one, to fix that.
